{{- if and .Values.openTelemetry.enabled (eq (.Values.openTelemetry.agent.kind | default "DaemonSet") "Deployment") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "sourcegraph.labels" . | nindent 4 }}
    deploy: sourcegraph
    app.kubernetes.io/component: otel-collector
  name: otel-agent
spec:
  ports:
    - name: grpc-otlp
      port: 4317
      protocol: TCP
      targetPort: grpc-otlp
    - name: http-otlp
      port: 4318
      protocol: TCP
      targetPort: http-otlp
  selector:
    {{- include "sourcegraph.selectorLabels" . | nindent 4 }}
    app: otel-agent
  type: ClusterIP
{{- end }}
