{{- if and .Values.executor.configureRbac .Values.executor.kubernetesJob.serviceAccount.create .Values.executor.kubernetesJob.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.executor.kubernetesJob.serviceAccount.name }}
  labels:
    category: rbac
    deploy: sourcegraph
    sourcegraph-resource-requires: cluster-admin
    app.kubernetes.io/component: executor
{{- with .Values.executor.kubernetesJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.executor.kubernetesJob.serviceAccount.automountToken }}
{{- end }}
