{{- if .Values.searcher.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.searcher.name }}
spec:
  {{- toYaml .Values.searcher.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      {{- include "sourcegraph.selectorLabels" . | nindent 6 }}
      app: searcher
{{- end }}
