apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: executor
    deploy: sourcegraph
    app.kubernetes.io/component: executor
  name: docker-config
data:
  daemon.json: |
    {{- $config := .Values.dind.daemonConfig | deepCopy }}
    {{- if .Values.dind.gVisor.enabled }}
    {{- $config = mergeOverwrite $config .Values.dind.gVisor.daemonConfig }}
    {{- end }}
    {{- $config | toPrettyJson | nindent 4 }}
