apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: executor
    deploy: sourcegraph
    app.kubernetes.io/component: executor
  name: docker-config
data:
  daemon.json: |
    {{- .Values.dind.daemonConfig | toPrettyJson | nindent 4 }}
