{{- if .Values.codeIntelDB.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: codeintel-db
    deploy: sourcegraph
  {{- if .Values.codeIntelDB.storageAnnotations }}
  annotations:
    {{- toYaml .Values.codeIntelDB.storageAnnotations | nindent 4 }}
  {{- end }}
  name: {{ default "codeintel-db" .Values.codeIntelDB.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.codeIntelDB.storageSize }}
  storageClassName: {{ .Values.storageClass.name }}
  {{- if .Values.codeIntelDB.volumeName }}
  volumeName: {{ .Values.codeIntelDB.volumeName }}
  {{- end }}
{{- end }}
