{{- if .Values.jaeger.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "sourcegraph.jaeger.labels" . | nindent 4 }}
    deploy: sourcegraph
    app.kubernetes.io/component: all-in-one
    app: jaeger
  name: {{ .Values.jaeger.name }}
data:
  jaeger-config.yaml: |
    {{- toYaml .Values.jaeger.config | nindent 4 }}
{{- end }}
