{{- if and .Values.redisStore.enabled .Values.redisStore.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.redisStore.name }}
spec:
  {{- toYaml .Values.redisStore.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      {{- include "sourcegraph.selectorLabels" . | nindent 6 }}
      app: redis-store
{{- end }}
